### PR TITLE
SepIntegration & rush cost changes #2

### PR DESCRIPTION
**Pull request by siimav**
This time with all the conflicts resolved and up-to-date with your master.
After the merge I added 2 additional changes. 
First one is to disable the Switch editor button when editing an existing vessel from the build queue. This causes inconsistencies about which queue built the vessel and from which one it was finally launched.
This Second one is specifically for RP-1 and disables the transfer between VAB and SPH queues functionality that you recently added. I find that one a bit too cheaty as you can build most of the vessel on the faster queue and then transfer it over to the slower one in the end.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
This is a very good point.  What would you think about allowing a transfer from one queue to the other only on the condition that the destination queue is either the same speed or slower?

> This Second one is specifically for RP-1 and disables the transfer between VAB and SPH queues functionality that you recently added. I find that one a bit too cheaty as you can build most of the vessel on the faster queue and then transfer it over to the slower one in the end

**Comment by linuxgurugamer** [comment]
I assume that the RO csproj should be mostly ready for me to use?  Other than the build changes I need to do for my Jenkins server?

**Comment by siimav** [comment]
>This is a very good point. What would you think about allowing a transfer from one queue to the other only on the condition that the destination queue is either the same speed or slower?

Had a quick look at the code again and it appears to me that the move is also enabled for vessels that are completed and in storage. So I don't honestly know what would be the best option here. For RP-1 I think this functionality should stay disabled either way. Ideally we would even add a check that ensures that planes could only be built inside the SPH and rockets inside VAB but there probably isn't an easy & foolproof way to differentiate between the two.

> I assume that the RO csproj should be mostly ready for me to use? Other than the build changes I need to do for my Jenkins server?

I was thinking that we should keep 2 separate project files. Your build server requires some changes and additional post-build events that wouldn't work too well for me. That's also why I renamed the csproj to have -RO suffix. It would probably be best if you changed the other project file to end with something like -LGG and use it specifically for your build pipeline.
Also it's now safe to remove the KSP1_4 precompiler symbols since we won't need to support KSP 1.3.x any longer. The RO symbol should probably stay so that I could exclude some lines that are used by your build process.

**Comment by linuxgurugamer** [comment]
If you are going to bundle in mod DLLs, you have to make sure they are in the same location as the normal mod.  Putting them into the KCT/Plugins directory is very bad, gave me no end of grief until I realized what was going on

**Pull request merged**
