### PR TITLE
use modifier keys to buy or spend multiple upgrade points at once

### PR DESCRIPTION
**Pull request by todi**
Use shift/ctrl/alt modifier keys to buy or spend 5/100/all available upgrade points.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Very nice idea.

A few things:

First, a complete description of what each does.  I think you want the following, please confirm.

Modifier    buy/spend
shift               5
ctrl               100 (if available)
alt                 all available

Second, instead of using LeftAlt/RightAlt, please change the code to use the modifier key, since it is different on different systems

Third, I don't see anything which would clue the player into the availability of these new modifier keys.  

Fourth, have you thought about just adding three more buttons on each row instead of adding additional keys to possibly confuse the player? 

Fifth, rather than have the values hard-coded to 5 and 100, did you think about having a way to allow the player to specify what they would want each value to be?

**Comment by linuxgurugamer** [comment]
I've posted looking for input regard this change in the forum here: https://forum.kerbalspaceprogram.com/index.php?/topic/182877-173-18x-kerbal-construction-time-unrapid-planned-assembly/&do=findComment&comment=3716884

Please feel free to join in the discussion

**Comment by todi** [comment]
Thank you for looking over it. I've answered on the forum thread as well, but just to address your (excellent) points:

1. Your description is exactly right.
2. and 5. I'll change if it should be decided to use my version instead of yours
3. and 4. I've answered on the forum

**Comment by siimav** [comment]
Looks like something went wrong during the merge. Getting a compile error because `availablePoints` is defined as both a static and local variable: https://github.com/todi/KCT/blob/19f0a69b6b738065dc1283b875e9a9df7c86d4b6/Kerbal_Construction_Time/KCT_GUI.cs#L1763

**Comment by linuxgurugamer** [comment]
Yes.  I fixed it on my local, just remove the "int" from the second one, I haven't yet pushed the changes.  Will try to do that tonight, after I do an initial implementation of the configs for the airlaunch for stock.

**Pull request merged**
